name: "Build and deploy frontend"
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/*.yml'

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      environment:
        description: 'Which environment to update.'
        type: choice
        required: true
        default: dev
        options:
        - dev
        - uat


jobs:
  deploy:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    name: Build and deploy frontend manually
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - name: Configure AWS Credentials
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
        uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Build project
        run: |
          npm build     
      - name: Copy files S3 Hosting bucket
        run: |
          aws s3 sync dist/* s3://${{ env.S3_ENDPOINT_URL }}
      - name: Create invalidation for Cloudfront Distribution
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION }}